# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b1d35339-4b0f-4dfb-82c7-e77524b8d5df";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FC90-2D86";
      fsType = "vfat";
    };

  fileSystems."/backups" =
    { device = "/dev/disk/by-uuid/bc70d2b7-da87-4353-9ea0-757b9a6ce63c";
      fsType = "ext3";
    };

  fileSystems."/media" =
    { device = "/dev/disk/by-uuid/a856ba11-588a-469c-9033-fd907a9d99a0";
      fsType = "ext3";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/161fe3a6-cdc9-4c8a-9e24-d6213f28eb4a"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
