# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b1d35339-4b0f-4dfb-82c7-e77524b8d5df";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FC90-2D86";
      fsType = "vfat";
    };

  #fileSystems."/root/scripts/Backup/backups" =
  #  { device = "/dev/disk/by-uuid/e199502c-5dcb-4fdc-92f7-1bc3702c2e01";
  #    fsType = "ext4";
  #  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/161fe3a6-cdc9-4c8a-9e24-d6213f28eb4a"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
