#!/usr/bin/env bash

# Preview theme with base16-shell-preview
#
# git clone https://github.com/chriskempson/base16-shell /tmp/base16-shell
# BASE16_SHELL=/tmp/base16-shell nix-shell -p base16-shell-preview

# Args (WIP)
# 1 -> Path to wallpapers folder
# 2 -> Specific wallpaper file to use in wallpaper folder
# 3 -> Preset theme
# 4 -> If not null, use light theme

reload_dunst() {
  pkill dunst
  dunst&
}

# Wpg install
if [[ ! -L ~/.config/wpg/templates/gtk2 ]] || [[ ! -L ~/.config/wpg/templates/gtk3.0 ]] || [[ ! -L ~/.config/wpg/templates/dunstrc ]]
then
  mkdir -p ~/.themes
  mkdir -p ~/.config/dunst

  wpg-install.sh -g -i #-d

  # wpg-install.sh install Dunst template from
  # https://github.com/deviantfero/wpgtk-templates/tree/master/dunst
  # But I use a custom config, so manually link "dunstrc.base"
  # dunstrc will be generated by the wpg command later on
  rm -rf ~/.config/dunst/dunstrc
  ln -sf ~/.config/wpg/templates/dunstrc ~/.config/dunst/dunstrc
fi

# Generate schemes for all wallpaper
wpg -a $1/* > /dev/null

# If no second argument, take a random wallapper
  if [ -z "$2" ]; then
  echo "[+] Using random wallpaper"
  wpg -m
  else
    echo "[+] Using wallpaper $2"
  wpg -s $2
fi
# If third argument, use a preset color scheme, otherwise, generate from wallpaper
if [ ! -z "$3" ]; then
  if [ -z "$4" ]; then
  echo "[+] Using preset theme: $3"
  wpg --theme $3
  else
  echo "[+] Using light theme"
  wpg -L --theme $3
  fi

fi

# Update Emacs
# TODO: Check this
# kill -USR1 $(pgrep emacs)

# Restart dunst
reload_dunst

# Start pywalfox daemon
# Setup pywall for Firefox if not already
#if [ ! -f ~/.mozilla/native-messaging-hosts/pywalfox.json ]; then
  pywalfox install
#fi
pkill pywalfox
pywalfox start&
#pywalfox update

# Wait for network before starting Firefox and Thunderbird
while ! systemctl is-active --quiet network-online.target; do sleep 3; done;

# pgrep might be missing, prefer ps
# Need [.] to not return ps process as result
# https://stackoverflow.com/a/8965530
if ! ps -aux | grep "[.]firefox">/dev/null
then
  echo "[+] Firefox not running. Starting..."
  firefox&
fi

if ! ps -aux | grep "[.]thunderbird" > /dev/null
then
  echo "[+] Thunderbird not running. Starting..."
  thunderbird&
fi
